baseURL = 'https://Adrede.eu/'
languageCode = 'en-us'
title = 'PlusRED'
theme = 'blowfish'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.link]
        useEmbedded = 'auto'
